package demo.command.domain.topic;

import demo.command.base.AbstractEvent;
import demo.command.domain.user.UserProfileUpdatedEvent;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : TopicStateUpdatedEventvent&oo
//  @ File Name : TopicStateUpdatedEvent.java
//  @ Date : 2013/9/27
//  @ Author : bner
//
//

public class TopicStateUpdatedEvent extends AbstractEvent {

	private String topicId;

	public TopicStateUpdatedEvent() {
		super();
	}

	public String getTopicId() {
		return topicId;
	}

	public void setTopicId(String topicId) {
		this.topicId = topicId;
	}

	public String getOperatorId() {
		if (this.getSource() instanceof UserProfileUpdatedEvent) {
			return ((UserProfileUpdatedEvent) this.getSource()).getUserId();
		}
		return null;
	}

	@Override
	public boolean isNeedFilter() {
		return true;
	}

	@Override
	public Integer calOrder() {
		return 15;
	}


}
