package demo.command.domain.topic;

import demo.command.base.Event;
import demo.command.domain.feed.Feed;
import demo.command.domain.feed.ViewFeed;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : ViewFeedvent&oo
//  @ File Name : ViewFeed.java
//  @ Date : 2013/9/27
//  @ Author : bner
//
//

public class TopicViewFeed extends ViewFeed {

	private TopicViewFeed() {

	}

	public TopicViewFeed(Event source, Feed feed, String targetId,
			String sourceUserId) {
		super(source, feed, targetId, sourceUserId);
	}

	@Override
	protected Object clone() throws CloneNotSupportedException {
		TopicViewFeed newObj = new TopicViewFeed();
		this.copy(newObj);
		return newObj;
	}

}
