package demo.command.domain.feed;

import java.io.Serializable;
import java.util.Date;
import java.util.UUID;

import demo.command.base.Event;
import demo.command.base.EventBus;
import demo.command.base.EventFactory;
import demo.command.domain.user.UserVO;
import demo.infrastructure.DateUtil;
import demo.infrastructure.Identifyer;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Feedvent&oo
//  @ File Name : Feed.java
//  @ Date : 2013/9/27
//  @ Author : bner
//
//

public class Feed implements Identifyer, Cloneable, Serializable {

	private String id;

	private String type;

	private String message;

	private String eventId;

	private UserVO user = new UserVO();

	private String resourceId;

	private String resourceType;

	private Date createTime;

	public static String ResourceType_Blog = "Blog";

	public static String ResourceType_User = "User";

	public Feed() {
	}

	public Feed(Event event, UserVO user, String message, String resourceId,
			String resourceType) {
		this.id = UUID.randomUUID().toString();
		this.eventId = event.getId();
		this.user = user;
		this.type = event.getTypeInfo();
		this.message = message;
		this.resourceId = resourceId;
		this.resourceType = resourceType;
		this.createTime = DateUtil.getSysDate();

		FeedCreatedEvent feedCreatedEvent = EventFactory.createEvent(
				FeedCreatedEvent.class, event);
		feedCreatedEvent.setFeed(this);

		EventBus.send(feedCreatedEvent);
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public void setEventId(String eventId) {
		this.eventId = eventId;
	}

	public void setUser(UserVO user) {
		this.user = user;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getEventId() {
		return eventId;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getUserId() {
		return user.getId();
	}

	public void setUserId(String userId) {
		this.user.setId(userId);
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public UserVO getUser() {
		return user;
	}

	public String getResourceId() {
		return resourceId;
	}

	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	public String getResourceType() {
		return resourceType;
	}

	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	public Date getCreateTime() {
		return createTime;
	}

	@Override
	public String toString() {
		return "feedId : " + id + " message : " + message;
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		Feed newObj = new Feed();

		newObj.id = this.id;
		newObj.eventId = this.eventId;
		newObj.type = this.type;
		newObj.message = this.message;
		newObj.user = this.user;
		newObj.resourceId = this.resourceId;
		newObj.resourceType = this.resourceType;
		newObj.createTime = this.createTime;

		return newObj;
	}

}
