package demo.command.domain.feed;

import java.util.UUID;

import demo.command.base.Event;
import demo.command.base.EventBus;
import demo.command.base.EventFactory;
import demo.infrastructure.Identifyer;
import demo.infrastructure.JdbcTemplate;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : ViewFeedvent&oo
//  @ File Name : ViewFeed.java
//  @ Date : 2013/9/27
//  @ Author : bner
//
//

public abstract class ViewFeed implements Identifyer, Cloneable {

	private String id;

	private String feedId;

	private String targetId;

	private transient JdbcTemplate jdbcTemplate = new JdbcTemplate();

	public ViewFeed() {

	}

	public ViewFeed(Event source, Feed feed, String targetId,
			String sourceUserId) {
		this.id = UUID.randomUUID().toString();
		this.feedId = feed.getId();
		this.targetId = targetId;

		ViewFeedCreatedEvent viewFeedCreatedEvent = EventFactory.createEvent(
				ViewFeedCreatedEvent.class, source);
		viewFeedCreatedEvent.setViewFeed(this);

		EventBus.send(viewFeedCreatedEvent);
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFeedId() {
		return feedId;
	}

	public void setFeedId(String feedId) {
		this.feedId = feedId;
	}

	public String getTargetId() {
		return targetId;
	}

	public void setTargetId(String targetId) {
		this.targetId = targetId;
	}

	public FeedRepoVO getFeed() {
		return jdbcTemplate.find(feedId, FeedRepoVO.class);
	}

	@Override
	public String toString() {
		return "viewFeedId : " + id + " feedId : " + feedId + " message: "
				+ this.getFeed().getMessage();
	}

	protected ViewFeed copy(ViewFeed viewFeed) {

		viewFeed.id = this.id;
		viewFeed.feedId = this.feedId;
		viewFeed.targetId = this.targetId;

		return viewFeed;
	}
}
