package demo.command.domain.blog;

import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : BlogLikedEventvent&oo
//  @ File Name : BlogLikedEvent.java
//  @ Date : 2013/9/27
//  @ Author : bner
//
//

public class BlogTagAddedEvent extends BlogOperationEvent {

	@Override
	public String getType() {
		return "AddTagToBlog";
	}

}
