package demo.command.domain.blog;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : BlogLikedEventvent&oo
//  @ File Name : BlogLikedEvent.java
//  @ Date : 2013/9/27
//  @ Author : bner
//
//

public class BlogPublishedEvent extends BlogOperationEvent {

	private String content;

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Override
	public String getType() {
		return "Publish";
	}

}
