package demo.command.domain.blog;

import java.util.List;

import demo.command.base.AbstractEvent;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : BlogLikedEventvent&oo
//  @ File Name : BlogLikedEvent.java
//  @ Date : 2013/9/27
//  @ Author : abner
//
//

public abstract class BlogOperationEvent extends AbstractEvent {

	private BlogVO blog = new BlogVO();

	private String operId;

	public void setBlog(BlogVO blog) {
		this.blog = blog;
	}

	public BlogVO getBlog() {
		return blog;
	}

	public String getBlogId() {
		return blog.getId();
	}

	public void setBlogId(String blogId) {
		this.blog.setId(blogId);
	}

	public String getOwnerId() {
		return blog.getCreatorId();
	}

	public void setOwnerId(String ownerId) {
		this.blog.setCreatorId(ownerId);
	}

	public String getOperId() {
		return operId;
	}

	public void setOperId(String operId) {
		this.operId = operId;
	}

	public List<String> getTags() {
		return blog.getTags();
	}

	public void setTags(List<String> tags) {
		this.blog.setTags(tags);
	}

	public String getTagInfos() {
		StringBuffer info = new StringBuffer();
		for (String tag : getTags()) {
			info.append(tag);
			info.append(",");
		}
		return info.delete(info.length() - 1, info.length()).toString();
	}

	public abstract String getType();
}
