package demo.command.domain.blog;

import java.util.ArrayList;
import java.util.List;

import demo.command.base.AbstractEvent;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : BlogLikedEventvent&oo
//  @ File Name : BlogLikedEvent.java
//  @ Date : 2013/9/27
//  @ Author : bner
//
//

public class BlogStateUpdatedEvent extends AbstractEvent {

	private List<String> tags = new ArrayList<String>();

	public String getBlogId() {
		return ((BlogOperationEvent) this.getSource()).getBlogId();
	}

	public String getOwnerId() {
		return ((BlogOperationEvent) this.getSource()).getOwnerId();
	}

	public String getOperId() {
		return ((BlogOperationEvent) this.getSource()).getOperId();
	}

	public String getOperation() {
		return ((BlogOperationEvent) this.getSource()).getType();
	}

	public List<String> getTags() {
		return tags;
	}

	public void setTags(List<String> tags) {
		this.tags = tags;
	}

}
