package demo.command.domain.blog;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : BlogLikedEventvent&oo
//  @ File Name : BlogLikedEvent.java
//  @ Date : 2013/9/27
//  @ Author : bner
//
//

public class BlogPublishFinishedEvent extends BlogOperationEvent {
	@Override
	public String getType() {
		return "PublishFinish";
	}
	
}
