package demo.command.domain.user;

import java.util.Date;
import java.util.UUID;

import demo.command.base.Event;
import demo.command.domain.feed.Feed;
import demo.command.domain.feed.ViewFeed;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : ViewFeedvent&oo
//  @ File Name : ViewFeed.java
//  @ Date : 2013/9/27
//  @ Author : bner
//
//

public class UserViewFeed extends ViewFeed {

	private UserViewFeed() {

	}

	public UserViewFeed(Event source, Feed feed, String targetId,
			String sourceUserId) {
		super(source, feed, targetId, sourceUserId);
	}

	@Override
	protected Object clone() throws CloneNotSupportedException {
		UserViewFeed newObj = new UserViewFeed();
		this.copy(newObj);
		return newObj;
	}
}
