package demo.command.domain.user;

import java.util.List;

import demo.command.base.AbstractEvent;
import demo.command.domain.feed.Feed;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : UserProfileUpdatedEventvent&oo
//  @ File Name : UserProfileUpdatedEvent.java
//  @ Date : 2013/9/27
//  @ Author : bner
//
//

public class UserProfileUpdatedEvent extends AbstractEvent {

	private Feed feed;

	private UserVO user = new UserVO();

	public String getUserId() {
		return user.getId();
	}

	public Feed getFeed() {
		return feed;
	}

	public void setFeed(Feed feed) {
		this.feed = feed;
	}

	public void setUserId(String userId) {
		this.user.setId(userId);
	}

	public List<String> getTags() {
		return this.user.getTags();
	}

	public void setTags(List<String> tags) {
		this.user.setTags(tags);
	}

	public boolean isSelf(String userId) {
		return this.getUserId().equals(userId);
	}

	public boolean isOperator() {
		return this.feed != null;
	}

	public boolean isOwner() {
		return this.feed == null;
	}

	@Override
	public boolean isNeedFilter() {
		return true;
	}

	@Override
	public Integer calOrder() {
		if (this.isOperator()) {
			return 20;
		} else {
			return 10;
		}
	}

}
