package demo.command.domain.user;

import java.util.List;

import demo.command.base.AbstractEvent;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : BlogLikedEventvent&oo
//  @ File Name : BlogLikedEvent.java
//  @ Date : 2013/9/27
//  @ Author : bner
//
//

public class UserTagAddedEvent extends AbstractEvent {

	private String userId;

	private List<String> tags;

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public List<String> getTags() {
		return tags;
	}

	public void setTags(List<String> tags) {
		this.tags = tags;
	}

	public String getTagInfos() {
		if (tags != null && tags.size() > 0) {
			StringBuffer info = new StringBuffer();
			for (String tag : tags) {
				info.append(tag);
				info.append(",");
			}
			return info.delete(info.length() - 1, info.length()).toString();
		} else {
			return null;
		}
	}

}
