package demo.command.base;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;

import demo.infrastructure.CreatedIdentifyer;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : EventTeamvent&oo
//  @ File Name : EventTeam.java
//  @ Date : 2013/9/27
//  @ Author : bner
//
//

public class EventTeam implements Comparable<EventTeam>, CreatedIdentifyer {

	private String id;
	private Date createTime;

	private transient List<Event> events = new ArrayList<Event>();

	private transient MongoDBTemplate mongoDBTemplate = new MongoDBTemplate();

	public EventTeam() {
		this.id = UUID.randomUUID().toString();
		this.createTime = new Date();
	}

	public String getId() {
		return id;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public List<Event> getEvents() {
		return events;
	}

	public void addEvent(Event event) {
		this.events.add(event);
		event.setEventTeam(this);
	}

	public void save() {
		mongoDBTemplate.save(EventRepository.EventTeam, this);
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		EventTeam other = (EventTeam) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public int compareTo(EventTeam o) {
		return this.createTime.compareTo(o.createTime);
	}

}
