package demo.command.base;

import java.util.Date;
import java.util.Map;

import demo.infrastructure.CreatedIdentifyer;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Eventvent&oo
//  @ File Name : Event.java
//  @ Date : 2013/9/27
//  @ Author : bner
//
//

public interface Event extends Comparable<Event>, CreatedIdentifyer {

	void setEventTeam(EventTeam eventTeam);

	EventTeam getEventTeam();

	Event getSource();

	void setSource(Event event);

	<T extends Event> T getTheSource(Class<T> type);

	Date getCreateTime();

	boolean isNeedFilter();

	Integer calOrder();

	boolean isPersistent();

	String getTypeInfo();

	void save();

	void load(Map<String, EventTeam> eventTeams, Map<String, Event> events);

	void loadSource(Map<String, Event> events);
}
