package demo.command.base;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Handlervent&oo
//  @ File Name : Handler.java
//  @ Date : 2013/9/27
//  @ Author : bner
//
//

public interface Handler<T extends Event> {

	public void handle(T event);

	public void destory() throws Exception;

}
